version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /path/to/your/credentials.json:/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - /path/to/your/credentials.json:/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
